spring:
  profiles:
    include: oauth,real-db
  session:
    store-type: jdbc
---
spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://sb2-ws-db.coyu5dutbhiu.ap-northeast-2.rds.amazonaws.com:3306/
      username: syno
      password: syno1234!
      driver-class-name: org.mariadb.jdbc.Driver
